name: GitHub Repo Builder

on:
  workflow_call:
    inputs:
      technology:
        type: choice
        default: 'dotnet'
        required: true
        description: 'Choose your technology stack'
        options:
          - dotnet
          - typescript
      name:
        type: string
        required: true
        
jobs:

  builder:
    name: 'Builder'
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: 'Create repo from template'
        run: |
          gh repo create Krusty93/${{ inputs.name }} \
            --private \
            --disable-wiki \
            --template Krusty93/${{ inputs.technology }}-template
